//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBL { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaCTSP { get; set; }
        public string NoiDungBL { get; set; }
        public Nullable<System.DateTime> NgayBL { get; set; }
    
        public virtual ChiTietSP ChiTietSP { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
